#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# DWM Status 
#dwmstatus 2>&1 >/dev/null &

# DWM Bar 
/home/id10t/Scripts/dwm-bar/dwm_bar.sh &

# Screen 
xrandr --newmode "1920x1080"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync&&
xrandr --addmode Virtual-1 1920x1080&&
xrandr --output Virtual-1 --mode 1920x1080

# Compositor 
picom -f &

# Wallpaper
nitrogen --restore &

# DWM Loop 
while true; do
    dwm >/dev/null 2>&1
done

# Execute DWM 
while true; do
    # Log stderror to a file
    #dwm 2> ~/.dwm.log
    # No error logging
    dwm >/dev/null 2>&1
done
